# Site settings
title: "Chase Cargill"
description: "Chase Cargill's Knowledge Base"
theme: jekyll-theme-minimal

# GitHub Pages settings
repository: your-github-username/your-repo-name
url: "https://chasecargill.com"  # If you're using a custom domain

github_username: ChaseC-130
linkedin_username: chase-cargill-31288b178
